# Generated by Django 4.0.5 on 2022-07-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
