# Generated by Django 4.0.6 on 2022-07-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
