# Generated by Django 4.0.5 on 2022-07-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_contact_is_verified_user_is_contact_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_contact_verified',
        ),
    ]
