# Generated by Django 4.0.5 on 2022-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_contact_remove_user_is_contact_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_contact_verified',
            field=models.BooleanField(default=False),
        ),
    ]
