# Generated by Django 4.0.6 on 2022-07-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_contact_is_verified_alter_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_contact_verified',
            field=models.BooleanField(default=False),
        ),
    ]
