# Generated by Django 4.0.5 on 2022-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_contact_user_is_contact_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_contact_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
