# Generated by Django 4.0.5 on 2022-07-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_menu_image_alter_addoncategory_id_alter_addonitem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_is_verified',
        ),
    ]
