# Generated by Django 4.0.6 on 2022-07-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_affiliate_menu_earnings_menu_item_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='menu',
        ),
    ]
