# Generated by Django 4.0.6 on 2022-07-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_items_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.menu'),
        ),
    ]
