# Generated by Django 4.0.6 on 2022-07-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_items_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='company',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='identity_proof',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='name',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='room',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='wallet_amount',
        ),
        migrations.AddField(
            model_name='guests',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
