# Generated by Django 4.0.6 on 2022-07-12 11:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_guests_company_remove_guests_identity_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=None),
        ),
    ]
