# Generated by Django 4.0.6 on 2022-07-12 11:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_role_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True, verbose_name=models.CharField(blank=True, max_length=100, null=True)), size=None),
        ),
    ]
