# Generated by Django 4.0.6 on 2022-07-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_coupon_created_at_coupon_updated_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
