# Generated by Django 4.0.6 on 2022-07-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_guests_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='updated_at',
        ),
    ]
