# Generated by Django 4.0.6 on 2022-07-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_role_created_at_role_permissions_role_role_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
