# Generated by Django 4.0.6 on 2022-07-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
