# Generated by Django 4.0.6 on 2022-07-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_guests_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
