# Generated by Django 4.0.6 on 2022-07-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_user_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phone_number',
            field=models.BigIntegerField(blank=True, max_length=255, null=True),
        ),
    ]
