# Generated by Django 4.0.6 on 2022-07-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_hotel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
