# Generated by Django 4.0.6 on 2022-07-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_hotel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_general_manager',
            field=models.BooleanField(default=False),
        ),
    ]
