# Generated by Django 4.0.6 on 2022-07-20 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_user_is_general_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hotel'),
        ),
    ]
